name: credit-risk-train
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3
  - numpy=1.26.4
  - pandas=2.2.1
  - scikit-learn=1.4.2
  - pip:
      - xgboost==2.0.3
      - mlflow==2.13.0
      - azureml-mlflow>=1.60.0  # Upgrade this to fix the tracking_uri bug
      - azureml-core>=1.60.0    # Upgrade this to keep it matched      
      - shap==0.45.0
      - matplotlib==3.8.4
      - seaborn==0.13.2
      - pyarrow
